webpackJsonp([4],{147:/*!***************************************!*\
  !*** multi ./src/sketches/current.js ***!
  \***************************************/
/*! no static exports found */
/*! all exports used */
function(e,a,o){e.exports=o(/*! ./src/sketches/current.js */148)},148:/*!*********************************!*\
  !*** ./src/sketches/current.js ***!
  \*********************************/
/*! exports provided:  */
/*! all exports used */
function(e,a,o){"use strict";Object.defineProperty(a,"__esModule",{value:!0});var t=o(/*! ../lib/core */0),r=(o(/*! ../plugins/drawStats */19),o(/*! ../plugins/memoryStats */20),o(/*! ../plugins/datGui */18),o(/*! ../plugins/viewportWebGL */30),o(/*! ../plugins/name */21),o(/*! ../plugins/health */26),o(/*! ../plugins/position */7),o(/*! ../plugins/motion */8),o(/*! ../plugins/thruster */29),o(/*! ../plugins/seeker */28),o(/*! ../plugins/collision */37),o(/*! ../plugins/bounce */35),o(/*! ../plugins/repulsor */59),o(/*! ../plugins/playerInputSteering */39),o(/*! ../plugins/hordeSpawn */58),o(/*! ../plugins/spawn */27),window.world=new t.World({systems:{ViewportWebGL:{debug:!0,container:"#game",followName:"hero1",zoom:.3},DrawStats:{},DatGui:{},PlayerInputSteering:{},Health:{},Motion:{},Position:{},Thruster:{},Seeker:{},Repulsor:{},Collision:{},Bounce:{},Spawn:{},HordeSpawn:{viewportSystemName:"ViewportWebGL",offscreenTTL:.5,spawnMargin:250,minCount:150,maxFrameSpawn:15,spawn:function(e,a){var o=200*Math.random()+100;r.insert({Sprite:{name:"mine",size:o,color:16720418},Health:{max:4*o*o},Spawn:{},Collidable:{},Bounce:{mass:4*o*o},Position:{x:e,y:a,rotation:2*Math.PI*Math.random()},Motion:{dx:0,dy:0,drotation:2*Math.PI*Math.random()},Thruster:{deltaV:2400+100*Math.random(),maxV:1200+200*Math.random()},Seeker:{targetName:"hero1",radPerSec:.5+.2*Math.random()},HordeSpawn:{}})}}}}));r.insert({Name:{name:"hero1"},Sprite:{name:"hero",size:150,color:3355647},Spawn:{},Collidable:{},Bounce:{damage:1e-4,mass:7e3},Position:{x:0,y:0,rotation:-Math.PI/2},Motion:{},Thruster:{deltaV:2800,maxV:1400,active:!1},PlayerInputSteering:{radPerSec:Math.PI}});for(var n=0,i=0;i>-15e3;i-=600)r.insert({Name:{name:"repulsor"+i},Sprite:{name:"repulsor",color:2263074},Position:{x:n,y:i},Motion:{},Repulsor:{range:600,force:300}}),n+=600*Math.random()-300;r.start();var s=r.getSystem("ViewportWebGL"),d=r.getSystem("HordeSpawn"),m=r.getSystem("DatGui"),l=m.gui;l.add(r,"isPaused"),l.add(r,"debug"),l.add(s,"zoom",s.options.zoomMin,s.options.zoomMax).listen(),l.add(s,"lineWidth",1,4).step(.5).listen(),["gridEnabled","followEnabled","cameraX","cameraY"].forEach(function(e){l.add(s,e).listen()});var p=s.cursorPosition;l.add(p,"x").listen(),l.add(p,"y").listen(),l.add(d,"spawnCount").listen()}},[147]);
//# sourceMappingURL=index.js.map