webpackJsonp([4],{147:/*!***************************************!*\
  !*** multi ./src/sketches/current.js ***!
  \***************************************/
/*! no static exports found */
/*! all exports used */
function(e,o,a){e.exports=a(/*! ./src/sketches/current.js */148)},148:/*!*********************************!*\
  !*** ./src/sketches/current.js ***!
  \*********************************/
/*! exports provided:  */
/*! all exports used */
function(e,o,a){"use strict";Object.defineProperty(o,"__esModule",{value:!0});var t=a(/*! ../lib/core */0),r=(a(/*! ../plugins/drawStats */19),a(/*! ../plugins/memoryStats */20),a(/*! ../plugins/datGui */18),a(/*! ../plugins/viewportWebGL */30),a(/*! ../plugins/name */21),a(/*! ../plugins/health */26),a(/*! ../plugins/position */7),a(/*! ../plugins/motion */8),a(/*! ../plugins/thruster */29),a(/*! ../plugins/seeker */28),a(/*! ../plugins/collision */37),a(/*! ../plugins/bounce */35),a(/*! ../plugins/repulsor */59),a(/*! ../plugins/playerInputSteering */39),a(/*! ../plugins/hordeSpawn */58),a(/*! ../plugins/spawn */27),window.world=new t.World({systems:{ViewportWebGL:{debug:!0,container:"#game",followName:"hero1",zoom:.3},DrawStats:{},MemoryStats:{},DatGui:{},PlayerInputSteering:{},Health:{},Motion:{},Position:{},Thruster:{},Seeker:{},Repulsor:{},Collision:{},Bounce:{},Spawn:{},HordeSpawn:{viewportSystemName:"ViewportWebGL",offscreenTTL:.5,spawnMargin:250,minCount:200,spawn:function(e,o){var a=200*Math.random()+100;r.insert({Sprite:{name:"mine",size:a,color:16720418},Health:{max:4*a*a},Spawn:{},Collidable:{},Bounce:{mass:4*a*a},Position:{x:e,y:o,rotation:2*Math.PI*Math.random()},Motion:{dx:0,dy:0,drotation:2*Math.PI*Math.random()},Thruster:{deltaV:2400+100*Math.random(),maxV:1200+200*Math.random()},Seeker:{targetName:"hero1",radPerSec:.5+.2*Math.random()},HordeSpawn:{}})}}}}));r.insert({Name:{name:"hero1"},Health:{max:4e3},Sprite:{name:"hero",size:150,color:3355647},Spawn:{},Collidable:{},Bounce:{damage:1e-4,mass:7e3},Position:{x:0,y:0,rotation:-Math.PI/2},Motion:{},Thruster:{deltaV:2800,maxV:1400,active:!1},PlayerInputSteering:{radPerSec:Math.PI},Repulsor:{range:600,force:300}});for(var n=0,i=0;i>-15e3;i-=600)r.insert({Name:{name:"repulsor"+i},Sprite:{name:"repulsor",color:2263074},Position:{x:n,y:i},Motion:{},Repulsor:{range:600,force:300}}),n+=600*Math.random()-300;r.start();var s=r.getSystem("ViewportWebGL"),d=r.getSystem("HordeSpawn"),l=r.getSystem("DatGui"),m=l.gui;m.add(r,"isPaused"),m.add(r,"debug"),m.add(s,"zoom",s.options.zoomMin,s.options.zoomMax).listen(),m.add(s,"lineWidth",1,4).step(.5).listen(),["gridEnabled","followEnabled","cameraX","cameraY"].forEach(function(e){m.add(s,e).listen()});var p=s.cursorPosition;m.add(p,"x").listen(),m.add(p,"y").listen(),m.add(d,"spawnCount").listen()}},[147]);
//# sourceMappingURL=index.js.map